name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          path: ${{ github.event.repository.name }}
      
            
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
            
      - name: Build `FreeType`
        run: dotnet build "${{ github.event.repository.name }}/source" -c Debug /p:Version=${VERSION}
      
      - name: Build `FreeType`
        run: dotnet build "${{ github.event.repository.name }}/source" -c Release /p:Version=${VERSION}
      
            
      - name: Pack `FreeType`
        run: dotnet pack "${{ github.event.repository.name }}/source" /p:Version=${VERSION} --no-build --output .

      - name: Add GitHub source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
            
      - name: Publish `FreeType` to GitHub registry
        run: dotnet nuget push SimulationTree.FreeType.${VERSION}.nupkg --source github --api-key ${API_KEY}
        env:
          API_KEY: ${{ secrets.NUGET_TOKEN_GITHUB }}
      
      - name: Publish `FreeType` to official registry
        run: dotnet nuget push SimulationTree.FreeType.${VERSION}.nupkg --source nuget.org --api-key ${API_KEY}
        env:
          API_KEY: ${{ secrets.NUGET_TOKEN_OFFICIAL }}